// Generated by CoffeeScript 1.9.0
(function() {
  var Editor, ModalView, NoteEditor,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __hasProp = {}.hasOwnProperty,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  ModalView = (function() {
    function ModalView(mapper, _at_content) {
      this.content = _at_content != null ? _at_content : [];
      if (!mapper) {
        throw "Mapper is undefined";
      }
      this.id = "modalview:" + (Math.random()) + ".0";
      this.ishidden = true;
      this.hideclass = "ui dimmer modals page transition hidden pl-hidden";
      this.showclass = "ui dimmer modals page transition visible active";
      this.itself = mapper.parseMapForParent(this.dom(), document.body);
      this.ison = false;
    }

    ModalView.prototype.dom = function() {
      return {
        type: "div",
        id: "" + this.id,
        cls: "" + this.hideclass,
        children: {
          type: "div",
          cls: "ui small modal transition visible active scrolling",
          children: this.content
        }
      };
    };

    ModalView.prototype.show = function(handler) {
      var a, _ref;
      if (this.ison) {
        return false;
      }
      a = (_ref = this.itself) != null ? _ref : document.getElementById(this.id);
      if (a != null) {
        a.className = "" + this.showclass;
      }
      this.ison = true;
      return typeof handler === "function" ? handler(true) : void 0;
    };

    ModalView.prototype.hide = function(handler) {
      var a, _ref;
      if (!this.ison) {
        return false;
      }
      a = (_ref = this.itself) != null ? _ref : document.getElementById(this.id);
      if (a != null) {
        a.className = "" + this.hideclass;
      }
      this.ison = false;
      return typeof handler === "function" ? handler(false) : void 0;
    };

    return ModalView;

  })();

  Editor = (function(_super) {
    __extends(Editor, _super);

    function Editor(mapper, meta) {
      var cancel, content, desc, extra, header, metacontent, ok, textarea, _ref;
      if (!mapper) {
        throw "Mapper is undefined";
      }
      _ref = ["Editor", "", meta != null ? meta : []], this.title = _ref[0], this.text = _ref[1], this.meta = _ref[2];
      header = {
        type: "div",
        cls: "ui tip attached label",
        title: "" + this.title
      };
      metacontent = {
        type: "div",
        cls: "meta-content pl-container-center",
        children: this.meta
      };
      textarea = {
        type: "textarea",
        title: "" + this.text
      };
      this.header = mapper.parseMapForParent(header);
      this.metaarea = mapper.parseMapForParent(metacontent);
      this.textarea = mapper.parseMapForParent(textarea);
      this.handler = null;
      content = {
        type: "div",
        cls: "ui segment",
        children: [
          this.header, content = {
            type: "div",
            cls: "ui items",
            children: {
              type: "div",
              cls: "item",
              children: {
                type: "div",
                cls: "content",
                children: [
                  this.metaarea, desc = {
                    type: "div",
                    cls: "description pl-container-center",
                    children: {
                      type: "div",
                      cls: "ui form",
                      children: {
                        type: "div",
                        cls: "field",
                        children: this.textarea
                      }
                    }
                  }, extra = {
                    type: "div",
                    cls: "ui compact basic segment pl-container-center",
                    children: [
                      ok = {
                        type: "div",
                        cls: "ui small secondary basic button",
                        title: "Ok",
                        onclick: (function(_this) {
                          return function() {
                            return typeof _this.callback === "function" ? _this.callback(true) : void 0;
                          };
                        })(this)
                      }, cancel = {
                        type: "div",
                        cls: "ui small secondary basic button",
                        title: "Cancel",
                        onclick: (function(_this) {
                          return function() {
                            return typeof _this.callback === "function" ? _this.callback(false) : void 0;
                          };
                        })(this)
                      }
                    ]
                  }
                ]
              }
            }
          }
        ]
      };
      Editor.__super__.constructor.call(this, mapper, content);
    }

    Editor.prototype.show = function(title, text, handler) {
      this.header.innerHTML = ("" + this.title) + (title ? " | " + title : "");
      this.textarea.value = text ? "" + text : "" + this.text;
      this.handler = handler != null ? handler : null;
      return Editor.__super__.show.call(this);
    };

    Editor.prototype.hide = function() {
      this.header.innerHTML = "" + this.title;
      this.textarea.value = this.text;
      this.handler = null;
      return Editor.__super__.hide.call(this);
    };

    Editor.prototype.callback = function(status) {
      if (status) {
        return typeof this.handler === "function" ? this.handler(status, this.textarea.value) : void 0;
      } else {
        return typeof this.handler === "function" ? this.handler(status) : void 0;
      }
    };

    return Editor;

  })(ModalView);

  NoteEditor = (function(_super) {
    __extends(NoteEditor, _super);

    function NoteEditor(_at_mapper, dropdownCenter) {
      var list, selectbtn, selecttags, tagselector;
      this.mapper = _at_mapper;
      this.tagsmenu = this.mapper.parseMapForParent({
        type: "div",
        cls: "menu selectable"
      });
      this.labels = this.mapper.parseMapForParent({
        type: "div",
        cls: "item"
      });
      this.selectedTags = [];
      tagselector = {
        type: "div",
        cls: "ui segment",
        children: {
          type: "div",
          cls: "ui horizontal list",
          children: [
            selecttags = {
              type: "div",
              cls: "item",
              children: {
                type: "div",
                cls: "ui floating dropdown",
                children: [
                  selectbtn = {
                    type: "div",
                    cls: "ui small basic button",
                    title: "Select tags"
                  }, this.tagsmenu
                ]
              }
            }, this.labels
          ]
        }
      };
      NoteEditor.__super__.constructor.call(this, mapper, tagselector);
      list = dropdownCenter.search(this.itself, (function(_this) {
        return function(status, parent, elem) {
          var _i, _len, _ref, _ref1, _results;
          _ref = ["", []], _this.labels.innerHTML = _ref[0], _this.selectedTags = _ref[1];
          _ref1 = parent.menu.childNodes;
          _results = [];
          for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
            elem = _ref1[_i];
            if (elem && elem._isselected_ && elem._tag_) {
              _this.mapper.parseMapForParent(elem._tag_.dom(true), _this.labels);
              _results.push(_this.selectedTags.push(elem._tag_));
            } else {
              _results.push(void 0);
            }
          }
          return _results;
        };
      })(this));
      this.dropdown = list && list.length > 0 ? list[0] : null;
    }

    NoteEditor.prototype.show = function(title, text, handler, alltags, notetags) {
      var elem, item, tag, x, _i, _j, _len, _len1, _ref, _ref1, _ref2, _ref3, _ref4;
      if (alltags == null) {
        alltags = [];
      }
      if (notetags == null) {
        notetags = [];
      }
      _ref = ["", "", []], this.tagsmenu.innerHTML = _ref[0], this.labels.innerHTML = _ref[1], this.selectedTags = _ref[2];
      for (_i = 0, _len = alltags.length; _i < _len; _i++) {
        tag = alltags[_i];
        item = {
          type: "div",
          id: "" + tag.id,
          cls: "item",
          title: "" + tag.name,
          text_last: true,
          children: {
            type: "div",
            cls: "ui " + tag.color + " empty circular label"
          }
        };
        elem = this.mapper.parseMapForParent(item, this.tagsmenu);
        elem._tag_ = tag;
      }
      if ((_ref1 = this.dropdown) != null) {
        _ref1.update(this.tagsmenu);
      }
      _ref2 = this.tagsmenu.childNodes;
      for (_j = 0, _len1 = _ref2.length; _j < _len1; _j++) {
        elem = _ref2[_j];
        if (_ref3 = elem.id, __indexOf.call((function() {
          var _k, _len2, _results;
          _results = [];
          for (_k = 0, _len2 = notetags.length; _k < _len2; _k++) {
            x = notetags[_k];
            _results.push(x.id);
          }
          return _results;
        })(), _ref3) >= 0) {
          if ((_ref4 = this.dropdown) != null) {
            _ref4.select(elem);
          }
          this.mapper.parseMapForParent(elem._tag_.dom(true), this.labels);
          this.selectedTags.push(elem._tag_);
        }
      }
      return NoteEditor.__super__.show.call(this, title, text, handler);
    };

    NoteEditor.prototype.callback = function(status) {
      if (status) {
        return typeof this.handler === "function" ? this.handler(status, this.textarea.value, this.selectedTags) : void 0;
      } else {
        return typeof this.handler === "function" ? this.handler(status) : void 0;
      }
    };

    return NoteEditor;

  })(Editor);

  if (this.Editor == null) {
    this.Editor = NoteEditor;
  }

}).call(this);
